[FIX] add required exception and context parameters to OdooRPC request events
I triggered and discovered this issues using locust's run_single_user() method used for debugging (see: https://docs.locust.io/en/stable/running-in-debugger.html)

My OdooLocustUser locustfiles triggered this exception :

[2024-06-03 16:23:59,295] dmuyshond-T590/ERROR/root: Uncaught exception in event handler:
Traceback (most recent call last):
  File "/home/dmuyshond/src/imio/locust-testcases/iavision-locust-testcases/venv/lib/python3.11/site-packages/locust/event.py", line 47, in fire
    handler(**kwargs)
TypeError: PrintListener.on_request() missing 2 required positional arguments: 'exception' and 'context'

I fixed it explicitely specifying (apparently) required and missing arguments 'context' and 'exception' in OdooLocustUser.py, inside the send() method, at the events.request.fire() methods.